// <auto-generated />
using System;
using ArmaRealMapWebSite.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArmaRealMapWebSite.Migrations
{
    [DbContext(typeof(ArmaRealMapContext))]
    [Migration("20220102121220_Compositions")]
    partial class Compositions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("ArmaRealMapWebSite.Entities.Assets.Asset", b =>
                {
                    b.Property<int>("AssetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetCategory")
                        .HasColumnType("INTEGER");

                    b.Property<float>("BoundingSphereDiameter")
                        .HasColumnType("REAL");

                    b.Property<float>("CX")
                        .HasColumnType("REAL");

                    b.Property<float>("CY")
                        .HasColumnType("REAL");

                    b.Property<float>("CZ")
                        .HasColumnType("REAL");

                    b.Property<string>("ClassName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClusterName")
                        .HasColumnType("TEXT");

                    b.Property<float>("Depth")
                        .HasColumnType("REAL");

                    b.Property<int>("GameModID")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Height")
                        .HasColumnType("REAL");

                    b.Property<float>("MaxX")
                        .HasColumnType("REAL");

                    b.Property<float>("MaxY")
                        .HasColumnType("REAL");

                    b.Property<float>("MaxZ")
                        .HasColumnType("REAL");

                    b.Property<float>("MinX")
                        .HasColumnType("REAL");

                    b.Property<float>("MinY")
                        .HasColumnType("REAL");

                    b.Property<float>("MinZ")
                        .HasColumnType("REAL");

                    b.Property<string>("ModelPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("TerrainBuilderTemplateXML")
                        .HasColumnType("TEXT");

                    b.Property<int>("TerrainRegions")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Width")
                        .HasColumnType("REAL");

                    b.HasKey("AssetID");

                    b.HasIndex("GameModID");

                    b.ToTable("Asset");
                });

            modelBuilder.Entity("ArmaRealMapWebSite.Entities.Assets.AssetPreview", b =>
                {
                    b.Property<int>("AssetPreviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetID")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .HasColumnType("BLOB");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssetPreviewID");

                    b.HasIndex("AssetID");

                    b.ToTable("AssetPreview");
                });

            modelBuilder.Entity("ArmaRealMapWebSite.Entities.Assets.GameMod", b =>
                {
                    b.Property<int>("GameModID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("GameModID");

                    b.ToTable("GameMod");
                });

            modelBuilder.Entity("ArmaRealMapWebSite.Entities.Assets.ObjectLibrary", b =>
                {
                    b.Property<int>("ObjectLibraryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Density")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("ObjectCategory")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Probability")
                        .HasColumnType("REAL");

                    b.Property<int>("TerrainRegion")
                        .HasColumnType("INTEGER");

                    b.HasKey("ObjectLibraryID");

                    b.ToTable("ObjectLibrary");
                });

            modelBuilder.Entity("ArmaRealMapWebSite.Entities.Assets.ObjectLibraryAsset", b =>
                {
                    b.Property<int>("ObjectLibraryAssetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetID")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("MaxZ")
                        .HasColumnType("REAL");

                    b.Property<float?>("MinZ")
                        .HasColumnType("REAL");

                    b.Property<int>("ObjectLibraryID")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("PlacementRadius")
                        .HasColumnType("REAL");

                    b.Property<float?>("Probability")
                        .HasColumnType("REAL");

                    b.Property<float?>("ReservedRadius")
                        .HasColumnType("REAL");

                    b.HasKey("ObjectLibraryAssetID");

                    b.HasIndex("AssetID");

                    b.HasIndex("ObjectLibraryID");

                    b.ToTable("ObjectLibraryAsset");
                });

            modelBuilder.Entity("ArmaRealMapWebSite.Entities.Assets.ObjectLibraryComposition", b =>
                {
                    b.Property<int>("ObjectLibraryCompositionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Depth")
                        .HasColumnType("REAL");

                    b.Property<float>("Height")
                        .HasColumnType("REAL");

                    b.Property<int>("ObjectLibraryID")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Probability")
                        .HasColumnType("REAL");

                    b.Property<float>("Width")
                        .HasColumnType("REAL");

                    b.HasKey("ObjectLibraryCompositionID");

                    b.HasIndex("ObjectLibraryID");

                    b.ToTable("ObjectLibraryComposition");
                });

            modelBuilder.Entity("ArmaRealMapWebSite.Entities.Assets.ObjectLibraryCompositionAsset", b =>
                {
                    b.Property<int>("ObjectLibraryCompositionAssetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Angle")
                        .HasColumnType("REAL");

                    b.Property<int>("AssetID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ObjectLibraryCompositionID")
                        .HasColumnType("INTEGER");

                    b.Property<float>("X")
                        .HasColumnType("REAL");

                    b.Property<float>("Y")
                        .HasColumnType("REAL");

                    b.Property<float>("Z")
                        .HasColumnType("REAL");

                    b.HasKey("ObjectLibraryCompositionAssetID");

                    b.HasIndex("AssetID");

                    b.HasIndex("ObjectLibraryCompositionID");

                    b.ToTable("ObjectLibraryCompositionAsset");
                });

            modelBuilder.Entity("ArmaRealMapWebSite.Entities.Maps.Map", b =>
                {
                    b.Property<int>("MapID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("CellSize")
                        .IsRequired()
                        .HasColumnType("REAL");

                    b.Property<int?>("GridSize")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<string>("MgrsBottomLeft")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Preview")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Resolution")
                        .IsRequired()
                        .HasColumnType("REAL");

                    b.Property<int>("TerrainRegion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Workshop")
                        .HasColumnType("TEXT");

                    b.HasKey("MapID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Map");
                });

            modelBuilder.Entity("ArmaRealMapWebSite.Entities.Assets.Asset", b =>
                {
                    b.HasOne("ArmaRealMapWebSite.Entities.Assets.GameMod", "GameMod")
                        .WithMany()
                        .HasForeignKey("GameModID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameMod");
                });

            modelBuilder.Entity("ArmaRealMapWebSite.Entities.Assets.AssetPreview", b =>
                {
                    b.HasOne("ArmaRealMapWebSite.Entities.Assets.Asset", "Asset")
                        .WithMany("Previews")
                        .HasForeignKey("AssetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("ArmaRealMapWebSite.Entities.Assets.ObjectLibraryAsset", b =>
                {
                    b.HasOne("ArmaRealMapWebSite.Entities.Assets.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArmaRealMapWebSite.Entities.Assets.ObjectLibrary", "ObjectLibrary")
                        .WithMany("Assets")
                        .HasForeignKey("ObjectLibraryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("ObjectLibrary");
                });

            modelBuilder.Entity("ArmaRealMapWebSite.Entities.Assets.ObjectLibraryComposition", b =>
                {
                    b.HasOne("ArmaRealMapWebSite.Entities.Assets.ObjectLibrary", "ObjectLibrary")
                        .WithMany("Compositions")
                        .HasForeignKey("ObjectLibraryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObjectLibrary");
                });

            modelBuilder.Entity("ArmaRealMapWebSite.Entities.Assets.ObjectLibraryCompositionAsset", b =>
                {
                    b.HasOne("ArmaRealMapWebSite.Entities.Assets.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArmaRealMapWebSite.Entities.Assets.ObjectLibraryComposition", "Composition")
                        .WithMany("Assets")
                        .HasForeignKey("ObjectLibraryCompositionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Composition");
                });

            modelBuilder.Entity("ArmaRealMapWebSite.Entities.Assets.Asset", b =>
                {
                    b.Navigation("Previews");
                });

            modelBuilder.Entity("ArmaRealMapWebSite.Entities.Assets.ObjectLibrary", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Compositions");
                });

            modelBuilder.Entity("ArmaRealMapWebSite.Entities.Assets.ObjectLibraryComposition", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
