//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameRealisticMap.Studio {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameRealisticMap.Studio.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Agricultural Building.
        /// </summary>
        internal static string AssetAgricultural {
            get {
                return ResourceManager.GetString("AssetAgricultural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Basket.
        /// </summary>
        internal static string AssetBasket {
            get {
                return ResourceManager.GetString("AssetBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bench.
        /// </summary>
        internal static string AssetBench {
            get {
                return ResourceManager.GetString("AssetBench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bus top Shelter.
        /// </summary>
        internal static string AssetBusStopShelter {
            get {
                return ResourceManager.GetString("AssetBusStopShelter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Church Building.
        /// </summary>
        internal static string AssetChurch {
            get {
                return ResourceManager.GetString("AssetChurch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commercial Building.
        /// </summary>
        internal static string AssetCommercial {
            get {
                return ResourceManager.GetString("AssetCommercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default Areas.
        /// </summary>
        internal static string AssetDefaultAreas {
            get {
                return ResourceManager.GetString("AssetDefaultAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fence.
        /// </summary>
        internal static string AssetFence {
            get {
                return ResourceManager.GetString("AssetFence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fire Hydrant.
        /// </summary>
        internal static string AssetFireHydrant {
            get {
                return ResourceManager.GetString("AssetFireHydrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forest Trees.
        /// </summary>
        internal static string AssetForest {
            get {
                return ResourceManager.GetString("AssetForest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forest Additional.
        /// </summary>
        internal static string AssetForestAdditional {
            get {
                return ResourceManager.GetString("AssetForestAdditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forest Edge.
        /// </summary>
        internal static string AssetForestEdge {
            get {
                return ResourceManager.GetString("AssetForestEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forest Radial.
        /// </summary>
        internal static string AssetForestRadial {
            get {
                return ResourceManager.GetString("AssetForestRadial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hedge.
        /// </summary>
        internal static string AssetHedge {
            get {
                return ResourceManager.GetString("AssetHedge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Historical Fort.
        /// </summary>
        internal static string AssetHistoricalFort {
            get {
                return ResourceManager.GetString("AssetHistoricalFort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hut.
        /// </summary>
        internal static string AssetHut {
            get {
                return ResourceManager.GetString("AssetHut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Individual Garage.
        /// </summary>
        internal static string AssetIndividualGarage {
            get {
                return ResourceManager.GetString("AssetIndividualGarage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Industrial.
        /// </summary>
        internal static string AssetIndustrial {
            get {
                return ResourceManager.GetString("AssetIndustrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Information Board.
        /// </summary>
        internal static string AssetInformationBoard {
            get {
                return ResourceManager.GetString("AssetInformationBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Map Config.
        /// </summary>
        internal static string AssetMapConfig {
            get {
                return ResourceManager.GetString("AssetMapConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Materials.
        /// </summary>
        internal static string AssetMaterials {
            get {
                return ResourceManager.GetString("AssetMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Military.
        /// </summary>
        internal static string AssetMilitary {
            get {
                return ResourceManager.GetString("AssetMilitary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nature.
        /// </summary>
        internal static string AssetNature {
            get {
                return ResourceManager.GetString("AssetNature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Objects.
        /// </summary>
        internal static string AssetObjects {
            get {
                return ResourceManager.GetString("AssetObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Picnic Table.
        /// </summary>
        internal static string AssetPicnicTable {
            get {
                return ResourceManager.GetString("AssetPicnicTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Post Box.
        /// </summary>
        internal static string AssetPostBox {
            get {
                return ResourceManager.GetString("AssetPostBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Radio Tower.
        /// </summary>
        internal static string AssetRadioTower {
            get {
                return ResourceManager.GetString("AssetRadioTower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recycling Container.
        /// </summary>
        internal static string AssetRecyclingContainer {
            get {
                return ResourceManager.GetString("AssetRecyclingContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Residential.
        /// </summary>
        internal static string AssetResidential {
            get {
                return ResourceManager.GetString("AssetResidential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retail Building.
        /// </summary>
        internal static string AssetRetail {
            get {
                return ResourceManager.GetString("AssetRetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Road.
        /// </summary>
        internal static string AssetRoad {
            get {
                return ResourceManager.GetString("AssetRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rocks.
        /// </summary>
        internal static string AssetRocks {
            get {
                return ResourceManager.GetString("AssetRocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rocks Additional.
        /// </summary>
        internal static string AssetRocksAdditional {
            get {
                return ResourceManager.GetString("AssetRocksAdditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scrub.
        /// </summary>
        internal static string AssetScrub {
            get {
                return ResourceManager.GetString("AssetScrub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scrub Additional.
        /// </summary>
        internal static string AssetScrubAdditional {
            get {
                return ResourceManager.GetString("AssetScrubAdditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scrub Radial.
        /// </summary>
        internal static string AssetScrubRadial {
            get {
                return ResourceManager.GetString("AssetScrubRadial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sculpture.
        /// </summary>
        internal static string AssetSculpture {
            get {
                return ResourceManager.GetString("AssetSculpture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Shed.
        /// </summary>
        internal static string AssetShed {
            get {
                return ResourceManager.GetString("AssetShed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statue.
        /// </summary>
        internal static string AssetStatue {
            get {
                return ResourceManager.GetString("AssetStatue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tree.
        /// </summary>
        internal static string AssetTree {
            get {
                return ResourceManager.GetString("AssetTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wall.
        /// </summary>
        internal static string AssetWall {
            get {
                return ResourceManager.GetString("AssetWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à War Memorial.
        /// </summary>
        internal static string AssetWarMemorial {
            get {
                return ResourceManager.GetString("AssetWarMemorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Watercourse.
        /// </summary>
        internal static string AssetWatercourse {
            get {
                return ResourceManager.GetString("AssetWatercourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Watercourse Radial.
        /// </summary>
        internal static string AssetWatercourseRadial {
            get {
                return ResourceManager.GetString("AssetWatercourseRadial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Water Tower.
        /// </summary>
        internal static string AssetWaterTower {
            get {
                return ResourceManager.GetString("AssetWaterTower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Water Well.
        /// </summary>
        internal static string AssetWaterWell {
            get {
                return ResourceManager.GetString("AssetWaterWell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wayside Cross.
        /// </summary>
        internal static string AssetWaysideCross {
            get {
                return ResourceManager.GetString("AssetWaysideCross", resourceCulture);
            }
        }
    }
}
