//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameRealisticMap.Studio {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameRealisticMap.Studio.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Advanced parameters.
        /// </summary>
        public static string AdvancedParameters {
            get {
                return ResourceManager.GetString("AdvancedParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arma 3 Map Config.
        /// </summary>
        public static string Arma3MapConfig {
            get {
                return ResourceManager.GetString("Arma3MapConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Agricultural Building.
        /// </summary>
        public static string AssetAgricultural {
            get {
                return ResourceManager.GetString("AssetAgricultural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Basket.
        /// </summary>
        public static string AssetBasket {
            get {
                return ResourceManager.GetString("AssetBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bench.
        /// </summary>
        public static string AssetBench {
            get {
                return ResourceManager.GetString("AssetBench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bus top Shelter.
        /// </summary>
        public static string AssetBusStopShelter {
            get {
                return ResourceManager.GetString("AssetBusStopShelter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Church Building.
        /// </summary>
        public static string AssetChurch {
            get {
                return ResourceManager.GetString("AssetChurch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commercial Building.
        /// </summary>
        public static string AssetCommercial {
            get {
                return ResourceManager.GetString("AssetCommercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Asset config file is missing..
        /// </summary>
        public static string AssetConfigFileIsMissing {
            get {
                return ResourceManager.GetString("AssetConfigFileIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default Areas.
        /// </summary>
        public static string AssetDefaultAreas {
            get {
                return ResourceManager.GetString("AssetDefaultAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fence.
        /// </summary>
        public static string AssetFence {
            get {
                return ResourceManager.GetString("AssetFence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fire Hydrant.
        /// </summary>
        public static string AssetFireHydrant {
            get {
                return ResourceManager.GetString("AssetFireHydrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forest Trees.
        /// </summary>
        public static string AssetForest {
            get {
                return ResourceManager.GetString("AssetForest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forest Additional.
        /// </summary>
        public static string AssetForestAdditional {
            get {
                return ResourceManager.GetString("AssetForestAdditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forest Edge.
        /// </summary>
        public static string AssetForestEdge {
            get {
                return ResourceManager.GetString("AssetForestEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forest Radial.
        /// </summary>
        public static string AssetForestRadial {
            get {
                return ResourceManager.GetString("AssetForestRadial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hedge.
        /// </summary>
        public static string AssetHedge {
            get {
                return ResourceManager.GetString("AssetHedge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Historical Fort.
        /// </summary>
        public static string AssetHistoricalFort {
            get {
                return ResourceManager.GetString("AssetHistoricalFort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hut.
        /// </summary>
        public static string AssetHut {
            get {
                return ResourceManager.GetString("AssetHut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Individual Garage.
        /// </summary>
        public static string AssetIndividualGarage {
            get {
                return ResourceManager.GetString("AssetIndividualGarage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Industrial.
        /// </summary>
        public static string AssetIndustrial {
            get {
                return ResourceManager.GetString("AssetIndustrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Information Board.
        /// </summary>
        public static string AssetInformationBoard {
            get {
                return ResourceManager.GetString("AssetInformationBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Map Config.
        /// </summary>
        public static string AssetMapConfig {
            get {
                return ResourceManager.GetString("AssetMapConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Materials.
        /// </summary>
        public static string AssetMaterials {
            get {
                return ResourceManager.GetString("AssetMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Military.
        /// </summary>
        public static string AssetMilitary {
            get {
                return ResourceManager.GetString("AssetMilitary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nature.
        /// </summary>
        public static string AssetNature {
            get {
                return ResourceManager.GetString("AssetNature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Objects.
        /// </summary>
        public static string AssetObjects {
            get {
                return ResourceManager.GetString("AssetObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Picnic Table.
        /// </summary>
        public static string AssetPicnicTable {
            get {
                return ResourceManager.GetString("AssetPicnicTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Post Box.
        /// </summary>
        public static string AssetPostBox {
            get {
                return ResourceManager.GetString("AssetPostBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Radio Tower.
        /// </summary>
        public static string AssetRadioTower {
            get {
                return ResourceManager.GetString("AssetRadioTower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recycling Container.
        /// </summary>
        public static string AssetRecyclingContainer {
            get {
                return ResourceManager.GetString("AssetRecyclingContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Residential.
        /// </summary>
        public static string AssetResidential {
            get {
                return ResourceManager.GetString("AssetResidential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retail Building.
        /// </summary>
        public static string AssetRetail {
            get {
                return ResourceManager.GetString("AssetRetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Road.
        /// </summary>
        public static string AssetRoad {
            get {
                return ResourceManager.GetString("AssetRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rocks.
        /// </summary>
        public static string AssetRocks {
            get {
                return ResourceManager.GetString("AssetRocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rocks Additional.
        /// </summary>
        public static string AssetRocksAdditional {
            get {
                return ResourceManager.GetString("AssetRocksAdditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assets configuration / style of map.
        /// </summary>
        public static string AssetsConfiguration {
            get {
                return ResourceManager.GetString("AssetsConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scrub.
        /// </summary>
        public static string AssetScrub {
            get {
                return ResourceManager.GetString("AssetScrub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scrub Additional.
        /// </summary>
        public static string AssetScrubAdditional {
            get {
                return ResourceManager.GetString("AssetScrubAdditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scrub Radial.
        /// </summary>
        public static string AssetScrubRadial {
            get {
                return ResourceManager.GetString("AssetScrubRadial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sculpture.
        /// </summary>
        public static string AssetSculpture {
            get {
                return ResourceManager.GetString("AssetSculpture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Shed.
        /// </summary>
        public static string AssetShed {
            get {
                return ResourceManager.GetString("AssetShed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statue.
        /// </summary>
        public static string AssetStatue {
            get {
                return ResourceManager.GetString("AssetStatue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tree.
        /// </summary>
        public static string AssetTree {
            get {
                return ResourceManager.GetString("AssetTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wall.
        /// </summary>
        public static string AssetWall {
            get {
                return ResourceManager.GetString("AssetWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à War Memorial.
        /// </summary>
        public static string AssetWarMemorial {
            get {
                return ResourceManager.GetString("AssetWarMemorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Watercourse.
        /// </summary>
        public static string AssetWatercourse {
            get {
                return ResourceManager.GetString("AssetWatercourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Watercourse Radial.
        /// </summary>
        public static string AssetWatercourseRadial {
            get {
                return ResourceManager.GetString("AssetWatercourseRadial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Water Tower.
        /// </summary>
        public static string AssetWaterTower {
            get {
                return ResourceManager.GetString("AssetWaterTower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Water Well.
        /// </summary>
        public static string AssetWaterWell {
            get {
                return ResourceManager.GetString("AssetWaterWell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wayside Cross.
        /// </summary>
        public static string AssetWaysideCross {
            get {
                return ResourceManager.GetString("AssetWaysideCross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Browse Assets.
        /// </summary>
        public static string BrowseAssets {
            get {
                return ResourceManager.GetString("BrowseAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Browse all available objects to pick the best ones to complete your assets configuration..
        /// </summary>
        public static string BrowseAssetsDescription {
            get {
                return ResourceManager.GetString("BrowseAssetsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can use map below to select an area (Ctrl+Press, or Alt+Press).
        /// </summary>
        public static string CoordinatesHint {
            get {
                return ResourceManager.GetString("CoordinatesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coordinates of center of map.
        /// </summary>
        public static string CoordinatesOfCenterOfMap {
            get {
                return ResourceManager.GetString("CoordinatesOfCenterOfMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à or south west of map.
        /// </summary>
        public static string CoordinatesSouthWestOfMap {
            get {
                return ResourceManager.GetString("CoordinatesSouthWestOfMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a Map Configuration.
        /// </summary>
        public static string CreateAMapConfiguration {
            get {
                return ResourceManager.GetString("CreateAMapConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A map configuration defines a square to extract from OpenStreeMap, and associate an assets configuration to use for the generation process..
        /// </summary>
        public static string CreateAMapConfigurationDescription {
            get {
                return ResourceManager.GetString("CreateAMapConfigurationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create an Assets Configuration.
        /// </summary>
        public static string CreateAnAssetsConfiguration {
            get {
                return ResourceManager.GetString("CreateAnAssetsConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An assets configuration defines the textures and objects to use to generate a map. You can create your our own configuration or use one of the built-in configuration..
        /// </summary>
        public static string CreateAnAssetsConfigurationDescription {
            get {
                return ResourceManager.GetString("CreateAnAssetsConfigurationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Download from official site (free).
        /// </summary>
        public static string DownloadFromOfficialSiteFree {
            get {
                return ResourceManager.GetString("DownloadFromOfficialSiteFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ✔ Found.
        /// </summary>
        public static string Found {
            get {
                return ResourceManager.GetString("Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generate areas only (faster).
        /// </summary>
        public static string GenerateAreasOnly {
            get {
                return ResourceManager.GetString("GenerateAreasOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generate id map image.
        /// </summary>
        public static string GenerateIdMapImage {
            get {
                return ResourceManager.GetString("GenerateIdMapImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generate Map for Arma 3.
        /// </summary>
        public static string GenerateMapForArma3 {
            get {
                return ResourceManager.GetString("GenerateMapForArma3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generate Mod for Arma 3.
        /// </summary>
        public static string GenerateModForArma3 {
            get {
                return ResourceManager.GetString("GenerateModForArma3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generate Preview.
        /// </summary>
        public static string GeneratePreview {
            get {
                return ResourceManager.GetString("GeneratePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generate raw satellite image.
        /// </summary>
        public static string GenerateRawSatelliteImage {
            get {
                return ResourceManager.GetString("GenerateRawSatelliteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generate satellite image.
        /// </summary>
        public static string GenerateSatelliteImage {
            get {
                return ResourceManager.GetString("GenerateSatelliteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generate with elevation.
        /// </summary>
        public static string GenerateWithElevation {
            get {
                return ResourceManager.GetString("GenerateWithElevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Getting Started.
        /// </summary>
        public static string GettingStarted {
            get {
                return ResourceManager.GetString("GettingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a Map configuration and an Asset configuration to use with..
        /// </summary>
        public static string GettingStartedDescription {
            get {
                return ResourceManager.GetString("GettingStartedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toolchain to generate real scale gaming maps from OpenStreetMap data..
        /// </summary>
        public static string HomeIntro {
            get {
                return ResourceManager.GetString("HomeIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current version supports only Arma 3.
        /// </summary>
        public static string HomeIntroLimit {
            get {
                return ResourceManager.GetString("HomeIntroLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ✔ Installed.
        /// </summary>
        public static string Installed {
            get {
                return ResourceManager.GetString("Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Install with Steam.
        /// </summary>
        public static string InstallWithSteam {
            get {
                return ResourceManager.GetString("InstallWithSteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Launch to approve license.
        /// </summary>
        public static string LaunchApproveLicense {
            get {
                return ResourceManager.GetString("LaunchApproveLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ❌ License not approved.
        /// </summary>
        public static string LicenseNotApproved {
            get {
                return ResourceManager.GetString("LicenseNotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Map size (square).
        /// </summary>
        public static string MapSizeSquare {
            get {
                return ResourceManager.GetString("MapSizeSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To select an area on the map :
        ///- From a corner, press Ctrl Key then press Left Mouse Button
        ///- From center, press Alt Key then press Left Mouse Button..
        /// </summary>
        public static string MapUsageHint {
            get {
                return ResourceManager.GetString("MapUsageHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à meters.
        /// </summary>
        public static string MetersUnit {
            get {
                return ResourceManager.GetString("MetersUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ❌ Not found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ❌ Not installed.
        /// </summary>
        public static string NotInstalled {
            get {
                return ResourceManager.GetString("NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open Arma3 Launcher.
        /// </summary>
        public static string OpenArma3Launcher {
            get {
                return ResourceManager.GetString("OpenArma3Launcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ⟳ Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Required Tools.
        /// </summary>
        public static string RequiredTools {
            get {
                return ResourceManager.GetString("RequiredTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à In order to configure or generate a map, some additional tools and configurations are required..
        /// </summary>
        public static string RequiredToolsDescription {
            get {
                return ResourceManager.GetString("RequiredToolsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Setup with Arma3 Tools.
        /// </summary>
        public static string SetupWithArma3Tools {
            get {
                return ResourceManager.GetString("SetupWithArma3Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This tool will allow you to generate ready-to-use mod..
        /// </summary>
        public static string ThisToolWillAllowYouToGenerateReadyToUseMod {
            get {
                return ResourceManager.GetString("ThisToolWillAllowYouToGenerateReadyToUseMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à View on OpenStreetMap.org.
        /// </summary>
        public static string ViewOnOpenStreetMapOrg {
            get {
                return ResourceManager.GetString("ViewOnOpenStreetMapOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ⚠ Recommanded.
        /// </summary>
        public static string WarnRecommanded {
            get {
                return ResourceManager.GetString("WarnRecommanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can also mount drive with your custom tool.
        /// </summary>
        public static string YouCanAlsoMountDriveWithYourCustomTool {
            get {
                return ResourceManager.GetString("YouCanAlsoMountDriveWithYourCustomTool", resourceCulture);
            }
        }
    }
}
